### ISSUE TITLE
Regarding the possibility of reactivating an activated Windows system

### ISSUE THREAD

**Issue by everglow01** [Anawaert/WPF-KMS-Activator#1]
![屏幕截图 2024-03-26 101929](https://github.com/Anawaert/WPF-KMS-Activator/assets/155972933/58d2b9ad-36f2-4c10-855e-fe26bac52b29)
The function that determines whether Windows is activated or not is not called.

**Comment by Anawaert** [comment]
[The newest release](https://github.com/Anawaert/WPF-KMS-Activator/releases/tag/1.2.0.0) has fixed the bug，as well as adds some new features.
Thanks for your feedback, and Anawaert will continue to improve the quality of  our softwares!
